export const ERROR_CONST = {
    THIS_FIELD: "This field",
    UNKNOWN: "Unknown",
    START_DATE: "start date",
    END_DATE: "end date",
    VALIDATIONS: {
        REQUIRED: "{{name}} is required",
        PATTERN: "The input does not match the required pattern. Please enter a valid value",
        EMAIL: "Please provide a valid email address",
        PHONE: "Please provide a valid phone number",
        CURRENCY: "Currency can take value up to 8 digits and 2 decimal places.",
        MIN_CURRENCY: "{{name}} must be greater than {{min}}.",
        ONLY_STRING: "Only alphabets and spaces are allowed",
        ONLY_STRING_NO_SPACE: "Only alphabets are allowed",
        ONLY_ALPHANUMERIC: "Only alphabets, numbers and spaces are allowed",
        ONLY_ALPHANUMERIC_NO_SPACE: "Only alphabets and numbers are allowed",
        MAX_LENGTH: "Maximum length allowed is {{length}} characters",
        MIN_LENGTH: "Minimum length required is {{length}} characters",
        DATE_PICKER_FILTER: "You cannot select this date as it is restricted",
        DATE_PICKER_MIN: "The selected {{name}} must be after the allowed date {{date}}",
        DATE_PICKER_MAX: "The selected {{name}} must be before the allowed date {{date}}",
        DATE_INVALID: "The {{name}} is invalid. Please choose a valid date",
        DATETIME_INVALID: "The {{name}} is invalid. Please enter a valid date",
        TIME_INVALID: "The {{name}} is invalid. Please enter a valid time",
        TIME_MIN: "The selected {{name}} is earlier than allowed time",
        TIME_MAX: "The selected {{name}} is later than allowed time",
        TIME_RANGE: "End time must be after start time",
        PAST_TIME_NOT_ALLOWED: "Start time must be later than the current time.",
        LESS_THAN_MAX_MARKS: "Passing marks must be less than or equal to Max marks.",
        LESS_THAN: "{{name}} must be less than {{compareName}}",
        LESS_THAN_OR_EQUAL: "{{name}} must be less than or equal to {{compareName}}",
        GREATER_THAN: "{{name}} must be greater than {{compareName}}",
        GREATER_THAN_OR_EQUAL: "{{name}} must be greater than or equal to {{compareName}}",
        PASSWORD_MISMATCH: "Passwords do not match.",
        SAME_AS_OLD: "New password cannot be the same as current password.",
        PASSWORD_PATTERN: "Password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, and one number.",
        FEE_TYPE_CODE: "Code must be exactly 3 uppercase letters without spaces.",
        DUPLICATE_HOLIDAY: "Holiday already exists on {{date}}."
    }
}